# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bazzite-kde-rocm
description: This is my personal OS image with kernel 6.12 LTS for ROCm support.

base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/kwizart/kernel-longterm-6.12/repo/fedora-43/kwizart-kernel-longterm-6.12-fedora-43.repo

    remove:
      - kernel
      - kernel-core
      - kernel-modules
      - kernel-modules-extra
      - kernel-modules-core
      - kernel-modules-akmods
      - kernel-devel-matched

    install:
      - kernel-longterm
      - kernel-longterm-core
      - kernel-longterm-devel
      - kernel-longterm-modules
      - kernel-longterm-modules-extra
      - rocminfo
